packaging/nix-installer: Nuke ciphersuite micromanaging
This was already dropped in [1]. The changes in rustup have been done a long
time ago. The more maintainable way forward is probably just relying on curl
and the tls stacks to use the sanest defaults possible. TLS v1.3 is already
used when talking to https://releases.nixos.org on any sane version of curl.
Micromanaging this would burden nix with keeping up with the defaults which
is probably better handled at the infrastructure level.

Additionally, we also straight-up embed expected content hashes for the binary
now at build-time so it's much less of a concern because our release artifacts
are immutable (tm).

[1]: https://github.com/NixOS/nix-installer/pull/121

diff --git a/packaging/nix-installer/nix-installer.in b/packaging/nix-installer/nix-installer.in
--- a/packaging/nix-installer/nix-installer.in
+++ b/packaging/nix-installer/nix-installer.in
@@ -2,7 +2,7 @@
 # shellcheck shell=dash
 
 # If you need an offline install, or you'd prefer to run the binary directly, head to
-# https://github.com/NixOS/nix-installer/releases then pick the version and platform
+# https://releases.nixos.org/?prefix=nix/nix-@nixVersion@ then pick the platform
 # most appropriate for your deployment target.
 #
 # This is just a little script that selects and downloads the right `nix-installer`. It does
@@ -286,7 +286,6 @@ downloader() {
   is_zsh && setopt local_options shwordsplit
 
   local _dld
-  local _ciphersuites
   local _err
   local _status
   local _retry
@@ -298,7 +297,7 @@ downloader() {
       if check_cmd wget; then
         _dld=wget
       else
-        err "curl installed with snap cannot be used to install Rust"
+        err "curl installed with snap cannot be used to install Nix"
         err "due to missing permissions. Please uninstall it and"
         err "reinstall curl with a different package manager (e.g., apt)."
         err "See https://github.com/boukendesho/curl-snap/issues/1"
@@ -318,25 +317,9 @@ downloader() {
   elif [ "$_dld" = curl ]; then
     check_curl_for_retry_support
     _retry="$RETVAL"
-    get_ciphersuites_for_curl
-    _ciphersuites="$RETVAL"
-    if [ -n "$_ciphersuites" ]; then
-      # shellcheck disable=SC2086
-      _err=$(curl $_retry --proto '=https' --tlsv1.2 --ciphers "$_ciphersuites" --silent --show-error --fail --location "$1" --output "$2" 2>&1)
-      _status=$?
-    else
-      warn "Not enforcing strong cipher suites for TLS, this is potentially less secure"
-      if ! check_help_for "$3" curl --proto --tlsv1.2; then
-        warn "Not enforcing TLS v1.2, this is potentially less secure"
-        # shellcheck disable=SC2086
-        _err=$(curl $_retry --silent --show-error --fail --location "$1" --output "$2" 2>&1)
-        _status=$?
-      else
-        # shellcheck disable=SC2086
-        _err=$(curl $_retry --proto '=https' --tlsv1.2 --silent --show-error --fail --location "$1" --output "$2" 2>&1)
-        _status=$?
-      fi
-    fi
+    # shellcheck disable=SC2086
+    _err=$(curl $_retry -sSfL "$1" -o "$2" 2>&1)
+    _status=$?
     if [ -n "$_err" ]; then
       warn "$_err"
       if echo "$_err" | grep -q 404$; then
@@ -346,28 +329,8 @@ downloader() {
     fi
     return $_status
   elif [ "$_dld" = wget ]; then
-    if [ "$(wget -V 2>&1 | head -2 | tail -1 | cut -f1 -d" ")" = "BusyBox" ]; then
-      warn "using the BusyBox version of wget.  Not enforcing strong cipher suites for TLS or TLS v1.2, this is potentially less secure"
-      _err=$(wget "$1" -O "$2" 2>&1)
-      _status=$?
-    else
-      get_ciphersuites_for_wget
-      _ciphersuites="$RETVAL"
-      if [ -n "$_ciphersuites" ]; then
-        _err=$(wget --https-only --secure-protocol=TLSv1_2 --ciphers "$_ciphersuites" "$1" -O "$2" 2>&1)
-        _status=$?
-      else
-        warn "Not enforcing strong cipher suites for TLS, this is potentially less secure"
-        if ! check_help_for "$3" wget --https-only --secure-protocol; then
-          warn "Not enforcing TLS v1.2, this is potentially less secure"
-          _err=$(wget "$1" -O "$2" 2>&1)
-          _status=$?
-        else
-          _err=$(wget --https-only --secure-protocol=TLSv1_2 "$1" -O "$2" 2>&1)
-          _status=$?
-        fi
-      fi
-    fi
+    _err=$(wget "$1" -O "$2" 2>&1)
+    _status=$?
     if [ -n "$_err" ]; then
       warn "$_err"
       if echo "$_err" | grep -q ' 404 Not Found$'; then
@@ -397,37 +360,6 @@ check_help_for() {
   else
     _category=""
   fi
-
-  case "$_arch" in
-
-  *darwin*)
-    if check_cmd sw_vers; then
-      local _os_version
-      local _os_major
-      _os_version=$(sw_vers -productVersion)
-      _os_major=$(echo "$_os_version" | cut -d. -f1)
-      case $_os_major in
-      10)
-        # If we're running on macOS, older than 10.13, then we always
-        # fail to find these options to force fallback
-        if [ "$(echo "$_os_version" | cut -d. -f2)" -lt 13 ]; then
-          # Older than 10.13
-          warn "Detected macOS platform older than 10.13"
-          return 1
-        fi
-        ;;
-      *)
-        if ! { [ "$_os_major" -eq "$_os_major" ] 2>/dev/null && [ "$_os_major" -ge 11 ]; }; then
-          # Unknown product version, warn and continue
-          warn "Detected unknown macOS major version: $_os_version"
-          warn "TLS capabilities detection may fail"
-        fi
-        ;; # We assume that macOS v11+ will always be okay.
-      esac
-    fi
-    ;;
-
-  esac
 
   for _arg in "$@"; do
     if ! "$_cmd" --help "$_category" | grep -q -- "$_arg"; then
@@ -464,93 +396,6 @@ check_curl_for_retry_support() {
   fi
 
   RETVAL="$_retry_part $_continue_part $_speed_limit_part"
-}
-
-# Return cipher suite string specified by user, otherwise return strong TLS 1.2-1.3 cipher suites
-# if support by local tools is detected. Detection currently supports these curl backends:
-# GnuTLS and OpenSSL (possibly also LibreSSL and BoringSSL). Return value can be empty.
-get_ciphersuites_for_curl() {
-  if [ -n "${RUSTUP_TLS_CIPHERSUITES-}" ]; then
-    # user specified custom cipher suites, assume they know what they're doing
-    RETVAL="$RUSTUP_TLS_CIPHERSUITES"
-    return
-  fi
-
-  local _openssl_syntax="no"
-  local _gnutls_syntax="no"
-  local _backend_supported="yes"
-  if curl -V | grep -q ' OpenSSL/'; then
-    _openssl_syntax="yes"
-  elif curl -V | grep -iq ' LibreSSL/'; then
-    _openssl_syntax="yes"
-  elif curl -V | grep -iq ' BoringSSL/'; then
-    _openssl_syntax="yes"
-  elif curl -V | grep -iq ' GnuTLS/'; then
-    _gnutls_syntax="yes"
-  else
-    _backend_supported="no"
-  fi
-
-  local _args_supported="no"
-  if [ "$_backend_supported" = "yes" ]; then
-    # "unspecified" is for arch, allows for possibility old OS using macports, homebrew, etc.
-    if check_help_for "notspecified" "curl" "--tlsv1.2" "--ciphers" "--proto"; then
-      _args_supported="yes"
-    fi
-  fi
-
-  local _cs=""
-  if [ "$_args_supported" = "yes" ]; then
-    if [ "$_openssl_syntax" = "yes" ]; then
-      _cs=$(get_strong_ciphersuites_for "openssl")
-    elif [ "$_gnutls_syntax" = "yes" ]; then
-      _cs=$(get_strong_ciphersuites_for "gnutls")
-    fi
-  fi
-
-  RETVAL="$_cs"
-}
-
-# Return cipher suite string specified by user, otherwise return strong TLS 1.2-1.3 cipher suites
-# if support by local tools is detected. Detection currently supports these wget backends:
-# GnuTLS and OpenSSL (possibly also LibreSSL and BoringSSL). Return value can be empty.
-get_ciphersuites_for_wget() {
-  if [ -n "${RUSTUP_TLS_CIPHERSUITES-}" ]; then
-    # user specified custom cipher suites, assume they know what they're doing
-    RETVAL="$RUSTUP_TLS_CIPHERSUITES"
-    return
-  fi
-
-  local _cs=""
-  if wget -V | grep -q '\-DHAVE_LIBSSL'; then
-    # "unspecified" is for arch, allows for possibility old OS using macports, homebrew, etc.
-    if check_help_for "notspecified" "wget" "TLSv1_2" "--ciphers" "--https-only" "--secure-protocol"; then
-      _cs=$(get_strong_ciphersuites_for "openssl")
-    fi
-  elif wget -V | grep -q '\-DHAVE_LIBGNUTLS'; then
-    # "unspecified" is for arch, allows for possibility old OS using macports, homebrew, etc.
-    if check_help_for "notspecified" "wget" "TLSv1_2" "--ciphers" "--https-only" "--secure-protocol"; then
-      _cs=$(get_strong_ciphersuites_for "gnutls")
-    fi
-  fi
-
-  RETVAL="$_cs"
-}
-
-# Return strong TLS 1.2-1.3 cipher suites in OpenSSL or GnuTLS syntax. TLS 1.2
-# excludes non-ECDHE and non-AEAD cipher suites. DHE is excluded due to bad
-# DH params often found on servers (see RFC 7919). Sequence matches or is
-# similar to Firefox 68 ESR with weak cipher suites disabled via about:config.
-# $1 must be openssl or gnutls.
-get_strong_ciphersuites_for() {
-  if [ "$1" = "openssl" ]; then
-    # OpenSSL is forgiving of unknown values, no problems with TLS 1.3 values on versions that don't support it yet.
-    echo "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
-  elif [ "$1" = "gnutls" ]; then
-    # GnuTLS isn't forgiving of unknown values, so this may require a GnuTLS version that supports TLS 1.3 even if wget doesn't.
-    # Begin with SECURE128 (and higher) then remove/add to build cipher suites. Produces same 9 cipher suites as OpenSSL but in slightly different order.
-    echo "SECURE128:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1:-VERS-DTLS-ALL:-CIPHER-ALL:-MAC-ALL:-KX-ALL:+AEAD:+ECDHE-ECDSA:+ECDHE-RSA:+AES-128-GCM:+CHACHA20-POLY1305:+AES-256-GCM"
-  fi
 }
 
 main "$@" || exit 1
